root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o ./bin/api ./cmd/api"
  bin = "./bin/api"
  delay = 1000
  exclude_dir = ["assets", "bin", "vendor", "tests", "docs", "deploy", "docker"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]
