apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopherplate
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gopherplate
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
