apiVersion: v1
kind: Secret
metadata:
  name: go-boilerplate-secrets
  labels:
    app: go-boilerplate
type: Opaque
stringData:
  # Em dev local, usamos secrets inline (NÃO fazer isso em prod!)
  DB_PASSWORD: "password"
  DB_DSN: "postgres://user:password@postgres-service:5432/entities?sslmode=disable"
