apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-boilerplate
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: go-boilerplate
          resources:
            requests:
              cpu: "300m"
              memory: "350Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
