apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
namespace: go-boilerplate-producao
images:
  - name: 409287786754.dkr.ecr.us-east-1.amazonaws.com/go-boilerplate
    newName: 241533123901.dkr.ecr.sa-east-1.amazonaws.com/go-boilerplate
    newTag: go-1
patches:
  - path: ingress-host-patch.yaml
    target:
      kind: Ingress
      name: go-boilerplate
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: go-boilerplate
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: go-boilerplate
