apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go-boilerplate-secrets
spec:
  refreshInterval: 240m

  secretStoreRef:
    name: aws-secrets-manager-cluster
    kind: ClusterSecretStore

  target:
    name: go-boilerplate-secrets
    creationPolicy: Owner

  # Sincronizar todos os valores do secret do AWS Secrets Manager
  dataFrom:
    - extract:
        key: "eks/producao/go-boilerplate"
