apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-boilerplate-sa
  labels:
    app: go-boilerplate
  annotations:
    # IRSA: eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/go-boilerplate-role
automountServiceAccountToken: false
