apiVersion: v1
kind: ServiceAccount
metadata:
  name: gopherplate-sa
  labels:
    app: gopherplate
  annotations:
    # IRSA: eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/gopherplate-role
automountServiceAccountToken: false
